### ISSUE TITLE
Generate a new Google Maps API key

### ISSUE THREAD

**Issue by AntonThoresson** [AlexTelon/FlexiCharge-Cross-Platform#223]
Since the key from the last year has expired, a new key has to be generated in order for the map to show up in the application

**Comment by AntonThoresson** [comment]
Alex talked about providing us with a new API key. The key will both be used by native squad and us.

**Comment by AlexTelon** [comment]
Related to https://github.com/AlexTelon/FlexiCharge-Android/issues/152
