### ISSUE TITLE
Update test-flexicharge-cross-platform workflow to the new versions to make it run correctly

### ISSUE THREAD

**Issue by AntonThoresson** [AlexTelon/FlexiCharge-Cross-Platform#224]
Under the perfrom test tab in the workflow:
Run flutter test --machine | tojunit > test-report.xml
The current Dart SDK version is 3.1.1.

Because flexicharge depends on splashscreen >=0.0.2 which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=1.20.1 <3.0.0'" must be 2.[12](https://github.com/AlexTelon/FlexiCharge-Cross-Platform/actions/runs/6118584764/job/16606944074#step:5:13).0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
Bad state: not started
Error: Process completed with exit code 1.

**Comment by Lundgr0in** [comment]
Seems to be solved by applying changes made in #229

**Comment by Lundgr0in** [comment]
## Proposed changes
![tests.yml_1](https://github.com/AlexTelon/FlexiCharge-Cross-Platform/assets/89662775/a2e576d6-deaf-4952-9879-57769dceb4a7)
![tests.yml_2](https://github.com/AlexTelon/FlexiCharge-Cross-Platform/assets/89662775/147a304d-eac7-44b2-a3de-3dafc1b73b18)
