### ISSUE TITLE
Investigate how to test the "charging session"

### ISSUE THREAD

**Issue by AntonThoresson** [AlexTelon/FlexiCharge-Cross-Platform#259]
Investigate how we can test the chargining session properly. API calls, parameters, request body etc etc

**Comment by Lundgr0in** [comment]
Looked at the possibility to write mock tests using _Mockito_ (a Flutter standard), but there seems to be incompatibilities with current packages and SDK.
Gives an error message (see below) which states that our "lower bound of SDK" is 1.0.0, which is not the case in our pubspec file.

Error message:
![Error message](https://github.com/AlexTelon/FlexiCharge-Cross-Platform/assets/89662775/2b6b9de7-8d38-4fb4-bf1b-e6cc42aebc91)

**Comment by Lundgr0in** [comment]
Could install _Mockito_ by running `flutter pub upgrade --major-versions`, which upgrades package dependencies, and then run  `flutter pub add dev:mockito`.
However, I'm unsure if this is wise to do since I don't really know how it affects the application.

**Comment by Lundgr0in** [comment]
To get the application running again I had to make changes in `qr_scanner_view.dart` and `qr_scanner_viewmodel.dart`, according to the [mobile_scanner documentation](https://pub.dev/packages/mobile_scanner), along with changing the Kotlin version in `build.gradle` under the android folder.

**Comment by Lundgr0in** [comment]
If there are issues with the size of the application, maybe consider making changes proposed in the [mobile_scanner documentation](https://pub.dev/packages/mobile_scanner#android).
Unsure if we use the bundled or unbundled verison (3-10 MB vs 600 KB size increase)
